# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

# Dependabot configuration: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#scheduleinterval

version: 2
# NOTE: Gradle Kotlin support is still missing: https://github.com/dependabot/dependabot-core/issues/2238
# NOTE: There's no "security updates only" for Docker: https://github.com/dependabot/dependabot-core/issues/1971
#       and there's no support for OS packages: https://github.com/dependabot/dependabot-core/issues/2129
updates:
  - package-ecosystem: docker
    directory: "/service"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/apigw"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/proxy"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      babel:
        patterns:
          - "@babel/*"
      fontawesome:
        patterns:
          - "@fortawesome/*"
      jest:
        patterns:
          - "@types/jest"
          - "jest*"
          - "ts-jest"
        exclude-patterns:
          - "jest-junit"
      prettier:
        patterns:
          - "prettier"
          - "eslint-config-prettier"
          - "eslint-plugin-prettier"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      sentry:
        patterns:
          - "@sentry/*"
      typescript:
        patterns:
          - "tslib"
          - "typescript"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
  - package-ecosystem: npm
    directory: "/apigw"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      jest:
        patterns:
          - "@types/jest"
          - "jest*"
          - "ts-jest"
        exclude-patterns:
          - "jest-junit"
      node-saml:
        patterns:
          - "@node-saml/*"
      prettier:
        patterns:
          - "prettier"
          - "eslint-config-prettier"
          - "eslint-plugin-prettier"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
