# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later
---
spring:
  application:
    name: evaka-message-service
  main:
    banner-mode: "off"
server:
  port: 8083
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO

fi:
  espoo:
    voltti:
      s3mock:
        url: http://s3.lvh.me:9876
