# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later
---
debug: true

spring:
  flyway:
    # In integration tests, Flyway is run manually and not via Spring Boot
    enabled: false
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      # Keep backwards-compatible health check path
      base-path: /
logging:
  level:
    fi:
      espoo:
        evaka: debug
        evaka.messaging: debug
    org:
      springframework:
        ws:
          client:
            MessageTracing:
              received: TRACE
              sent: DEBUG
          server:
            MessageTracing:
              received: TRACE
              sent: DEBUG

aws:
  region: eu-west-1

fee_decision_min_date: "2015-01-01"

fi:
  espoo:
    evaka:
      maxAttachmentsPerUser: 2
      message:
        enabled: false
    integration:
      dvv-modifications-service:
        password: ""
        productCode: ""
        url: ""
        userId: ""
        xRoadClientId: ""
      invoice:
        enabled: false
      koski:
        secret: ""
        source_system: TestSystemCode
        url: ""
        user: ""
      varda:
        basic_auth: ""
        url: ""
        source_system: SourceSystemVarda
    varda:
      force:
        sync: true
      organizer: Espoo
    voltti:
      auth:
        jwks:
          default:
            url: classpath:evaka-integration-test/jwks.json
      document:
        bucket:
          attachments: evaka-attachments-it
          clubdecision: evaka-clubdecisions-it
          daycaredecision: evaka-daycaredecisions-it
          paymentdecision: evaka-paymentdecisions-it
          vouchervaluedecision: evaka-vouchervaluedecisions-it
      vtj:
        client:
          password: ""
          username: ""
        test:
          use_actual_vtj: false
        xroad:
          address: https://fake.test
          client:
            instance: FI-TEST
            memberClass: MUN
            memberCode: 0101263-6
            subSystemCode: evaka-test
          service:
            instance: FI-TEST
            memberClass: GOV
            memberCode: 0245437-2
            serviceCode: HenkilonTunnusKysely
            serviceVersion: v1
            subSystemCode: VTJkysely
          trustStore:
            location: classpath:xroad/trustStore.jks
            password: password
            type: JKS
application:
  frontend:
    baseurl: https://foo.espoonvarhaiskasvatus.fi
    baseurl.sv: https://esbosmabarnspedagogik.fi
  email:
    address:
      fi: testemail_fi@test.com
      sv: testemail_sv@test.com
    name:
      fi: Test email sender fi
      sv: Test email sender sv

