# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later
---
evaka:
  database:
    maximum_pool_size: 20
  email:
    sender_address: "no-reply.evaka@espoo.fi"
    sender_name:
      fi: "Espoon Varhaiskasvatus"
      sv: "Esbo småbarnspedagogik"
  fee_decision:
    min_date: "2020-03-01"
  five_years_old_daycare:
    enabled: true
  max_attachments_per_user: 100
  redis:
    port: 6379
  s3mock:
    url: "http://localhost:9876"

spring:
  profiles:
    group:
      integration-test:
        - enable_varda_mock_integration_endpoint
        - enable_mock_dvv_api
      local:
        - enable_dev_api
        - enable_varda_mock_integration_endpoint
  main:
    banner-mode: "off"
  application:
    name: "evaka-service"
  datasource:
    continue-on-error: false
    driver-class-name: "org.postgresql.Driver"
    sqlScriptEncoding: "UTF-8"
    type: "com.zaxxer.hikari.HikariDataSource"
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"
server:
  port: 8888
  tomcat:
    connection-timeout: "70s"
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
      exposure:
        include: "health"
  endpoint:
    health:
      enabled: true
