# SPDX-FileCopyrightText: 2017-2022 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: '3.5'

services:
  keycloak-postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  smtp:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  keycloak:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      # Initial admin user via environment, required when running with a container
      # https://www.keycloak.org/server/configuration#_creating_the_initial_admin_user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Configuration options
      # https://www.keycloak.org/server/all-config?f=config
      # Database
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL_HOST: keycloak-postgres
      # Hostname v1 (Deprecated)
      KC_HOSTNAME_URL: "http://localhost:8080/auth"
      KC_HOSTNAME_ADMIN_URL: "http://localhost:8080/auth"
      # HTTP(S)
      KC_HTTP_ENABLED: "true"
      # Logging
      # KC_LOG_LEVEL: "debug"
    entrypoint: /configuration/entrypoint.sh
    command: ["start", "--optimized", "--log-console-output=json"]
    volumes:
      - ./compose-resources/configuration:/configuration
      - ./theme/evaka:/opt/jboss/keycloak/themes/evaka
    depends_on:
      - smtp
      - keycloak-postgres
      - dummy-suomifi

  dummy-suomifi:
    build:
      context: dummy-suomifi
    ports:
      - "9000:9000"

volumes:
  postgres_data:
      driver: local
