# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

# Use this compose file to extend docker-compose.yml when you want to run
# the latest published versions, e.g. for E2E testing.
version: '3.5'

services:
  evaka-proxy:
    image: ${FRONTEND_IMAGE:-ghcr.io/espoon-voltti/evaka/frontend-common}:${TAG:-master}
    build:
      context: ../frontend/
      additional_contexts: # requires docker compose 2.17.0 or newer
        customizations: ../frontend/src/lib-customizations/espoo
      cache_from:
        - ghcr.io/espoon-voltti/evaka/frontend-common:cache-${CACHE_TAG:-master}
        - ghcr.io/espoon-voltti/evaka/frontend-common:cache-master
    ports:
      - "9099:8080"
    environment:
      RESOLVER: "127.0.0.11 ipv6=off"
      ENDUSER_GW_URL: "http://api-gw:3000"
      INTERNAL_GW_URL: "http://api-gw:3000"
      RATE_LIMIT_CIDR_WHITELIST: "0.0.0.0/0;::/0"
      HTTP_SCHEME: "http"
    # Enable for debug logging
    #command: [nginx-debug, '-g', 'daemon off;']
    # Develop nginx
    #volumes:
    #  - ../frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
    depends_on:
      - api-gw
      - evaka-srv
      - s3-mock

  api-gw:
    image: ghcr.io/espoon-voltti/evaka/api-gateway:${TAG:-master}
    build:
      context: ../apigw/
      cache_from:
        - ghcr.io/espoon-voltti/evaka/api-gateway:cache-${CACHE_TAG:-master}
        - ghcr.io/espoon-voltti/evaka/api-gateway:cache-master
    ports:
      - "3000"
    hostname: api-gw
    depends_on:
      - valkey
      - evaka-srv
      - dummy-idp
    volumes:
      - ../apigw/config/test-cert:/home/evaka/test-cert
    environment:
      VOLTTI_ENV: local
      NODE_ENV: local
      EVAKA_SERVICE_URL: ${EVAKA_SERVICE_URL}
      COOKIE_SECRET: cookie_secret
      REDIS_HOST: ${EVAKA_REDIS_HOST}
      REDIS_PORT: ${EVAKA_REDIS_PORT}
      REDIS_DISABLE_SECURITY: "true"
      JWT_PRIVATE_KEY: /home/evaka/test-cert/jwt_private_key.pem
      ENABLE_DEV_API: "true"
      PRETTY_LOGS: "false"

  evaka-srv:
    image: ghcr.io/espoon-voltti/evaka/service:${TAG:-master}
    build:
      context: ..
      dockerfile: service/Dockerfile
      cache_from:
        - ghcr.io/espoon-voltti/evaka/service:cache-${CACHE_TAG:-master}
        - ghcr.io/espoon-voltti/evaka/service:cache-master
    ports:
      - "8888"
    hostname: evaka-srv
    depends_on:
      - db
      - s3-mock
    environment:
      VOLTTI_ENV: local
      SPRING_PROFILES_ACTIVE: local
      SPRING_PROFILES_INCLUDE: enable_dev_api,enable_mock_integration_endpoint
      JAVA_OPTS: -server -Djava.security.egd=file:/dev/./urandom -Xms1024m -Xss512k -Xmx1024m -XX:TieredStopAtLevel=1
      EVAKA_DATABASE_FLYWAY_USERNAME: ${EVAKA_SERVICE_FLYWAY_USERNAME}
      EVAKA_DATABASE_FLYWAY_PASSWORD: ${EVAKA_SERVICE_FLYWAY_PASSWORD}
      EVAKA_DATABASE_URL: jdbc:postgresql://${EVAKA_DATABASE_HOST}:${EVAKA_DATABASE_PORT}/${EVAKA_SERVICE_DATABASE_NAME}
      EVAKA_DATABASE_USERNAME: ${EVAKA_SERVICE_APPLICATION_USERNAME}
      EVAKA_DATABASE_PASSWORD: ${EVAKA_SERVICE_APPLICATION_PASSWORD}
      SPRING_MAIN_BANNER_MODE: "off"
      # DEBUG: "true"
      # LOGGING_LEVEL_FI_ESPOO_EVAKA: DEBUG
      EVAKA_ASYNC_JOB_RUNNER_DISABLE_RUNNER: "true"
      EVAKA_BUCKET_DECISIONS: evaka-daycaredecisions-dev
      EVAKA_BUCKET_FEE_DECISIONS: evaka-paymentdecisions-dev
      EVAKA_LOCAL_S3_URL: https://s3-mock:9191
      EVAKA_BUCKET_PROXY_THROUGH_NGINX: "true"
      ESPOO_INTEGRATION_INVOICE_ENABLED: "false"
      EVAKA_INTEGRATION_KOSKI_ENABLED: "false"
      EVAKA_INTEGRATION_SFI_ENABLED: "false"
      EVAKA_INTEGRATION_VARDA_URL: "http://localhost:8888/mock-integration/varda/api"
      EVAKA_INTEGRATION_BASIC_AUTH: ""
    restart: unless-stopped

volumes:
  db-data:
    driver: local
